def clustering(structured_array):
    '''Takes the structured numpy array generated by threshold.py and clusters
    the passed tracks based upon their entry and exit 4-vectors. Constraints
    on individual clusters will be determined empirically from simulation
    framework and is still open to discussion.'''
